### ISSUE TITLE
passport.deserializeuser not called,and ctx.isAuthenticated() always equals false

### ISSUE THREAD

**Issue by cheneyweb** [rkusa/koa-passport#100]
1. The following is my key package
"koa": "^2.2.0",
"koa-passport": "^3.0.0",
"koa-router": "^7.0.1",
"koa-session": "^5.0.0"

2. My problem is when I use "ctx.isAuthenticated()" to check if user login before, ctx.isAuthenticated() always equal false even user has login by passport.authenticate

3.The following is my code:

>
app.js

```
const session = require('koa-session')
const passport = require(__dirname + '/src/auth/passport_config.js')
const xauth = require('./src/auth/router_auth.js')

const app = new Koa()
app.proxy = true
app.keys = ['your-session-secret']
app.use(session(app))

app.use(bodyParser())

app.use(passport.initialize())
app.use(passport.session())
app.use(mount('/',xauth.routes()))
```

>
passport_config.js

```
const passport = require('koa-passport')
const LocalStrategy = require('passport-local')
const UserModel = require(__dirname + '/../../src/model/UserModel')

passport.use(new LocalStrategy(

    function(username, password, done) {
        UserModel.findOne({ username: username }).then(function(result) {
            if (result != null) {
                if (result.password == password) {
                    return done(null, result);
                } else {
                    log.error('密码错误');
                    return done(null, false, { message: '密码错误' })
                }
            } else {
                log.error('用户不存在');
                return done(null, false, { message: '用户不存在' })
            }
        }).catch(function(err) {
            log.error(err.message);
            return done(null, false, { message: err.message })
        });
    }
));

passport.serializeUser(function(user, done) {
    done(null, user);
});

passport.deserializeUser(function(user, done) {
    console.info(user)
    return done(null, user);
});
```
>
router_auth.js

```
const Router = require('koa-router')
const log = require('tracer').colorConsole({ level: require('config').get('log').level })
const router = new Router()
const passport = require(__dirname + '/passport_config.js')

router.post('/login', function(ctx, next) {
    return passport.authenticate('local', function(err, user, info, status) {
        if (user === false) {
            ctx.body = { success: false }
            ctx.throw(401)
        } else {
            ctx.body = { success: true }
            return ctx.login(user)
        }
    })(ctx, next)
})

router.post('/test', function(ctx, next) {
    if (ctx.isAuthenticated()) {
        console.info('认证通过')
        return next()
    } else {
        ctx.body = '非法访问'
    }
})

module.exports = router
```

I try http://localhost/login，it work
But I try http://localhost/test，it doesn't work，it is always false，and passport.deserializeUser has never been called

I am very looking forward to your help，and sorry for my pool english

**Comment by rkusa** [comment]
Hm, I do not see an error, yet. Is `passport.serializeUser` being called?

**Comment by rkusa** [comment]
I've updated a `koa-passport-example` branch to be more closely to what you are doing and it is working fine. Would you mind checking whether https://github.com/rkusa/koa-passport-example/tree/issue_100 does work for you?

**Comment by roks0n** [comment]
I encountered a similar problem and after debugging, I've noticed the issues was I created two instances of `KoaRouter`:
- one had the authentication (passport) logic
- the other had the login form and some other pages

I didn't check into more detail, but the session isn't shared between different KoaRouter instances.

**Comment by gyeongmin-ji** [comment]
I`m temporary used 
`export async function authenticatedUser(ctx: Router.IRouterContext, next: () => Promise<any>) {
    if (ctx.session.passport.user && ctx.session.passport.user.user) {
        ctx.state.user = ctx.session.passport.user.user;
        await next();
    } else {
        ctx.throw(401, 'authenticate please');
    }
}`

**Comment by rkusa** [comment]
Are there any updates on this issue? @gyeongmin-ji thanks for the workaround. Do you have a similar issue, which requires this workaround?

**Comment by mh8a** [comment]
I have a similar issue when using custom store with `koa-session`. When running the setup without custom store and keeping the session in the cookie everything works fine. When i add a custom store to hold session in a database `passport.deserializeUser` is never called, the whole authentication workflow ends after the `get`method of my store.

Currently i use:

```
"koa": "^2.4.1",
"koa-bodyparser": "^4.2.0",
"koa-passport": "^4.0.1",
"koa-session": "^5.5.0",
"passport-local": "^1.0.0"
```

I also already tried with `koa-session2` and `koa-body`. The result is the very same every time: Login works fine, the session is created and stored in the database via custom session store. When accessing a route behind the authentication Middleware `ctx.isAuthenticated()`will always return `false` without `passport.deserializeUser` ever being called.

Is there a working example with custom session store anywhere? Maybe it is an issue with return values of `koa-session`s `get` method?

The Auth Middleware looks like this:

```
.use(async(ctx, next) => {

    log('session info', ctx.session);
    log('state.user info', ctx.state.user);

    if (ctx.isAuthenticated()) {
      return next()
    } else {
      ctx.throw(401);
    }

  })
```

At that point `ctx.session`is what i returned from session stores `get` method, but `ctx.state.user` is undefined, which is not a surprise when `passport.deserializeUser`has never been called before. So it looks like `koa-session`is ready and holding the right session but `koa-passport`has done nothing so far.

Do i have to login the user manually via passport in the get method of my custom store for `koa-session`?

Thanks for any hint on this.

**Comment by peakman** [comment]
I had a similar issue with ctx.isAuthenticated() returning false when, with earlier versions of koa-passport it used to return true.  I think the change in behaviour arises from the fact that the isAuthenticated() function in passport tests against the request rather than the ctx.

I deliberately choose not to deserialise the user unless I need to and I was calling ctx.isAuthenticated() in my customAuth before the deserialsation.

The code from ghost helped me and the following code tells me whether or not I have authorised user:

  function hasAuthenitcatedUser(ctx) {
    return ctx.session && ctx.session.passport && ctx.session.passport.user 
  }

**Comment by jenkynolasco11** [comment]
I'm having the same issue, but my situation is a bit weird. This is my code:

```
import Router from 'koa-router'
import passport from 'koa-passport'
import { setUserData } from '../../utils'
import { User, Bus } from '../../../models'

const isAuthenticated = async (ctx, next) => {
  try {
    if(ctx.isAuthenticated()) {
      const { user } = ctx.state
    
      const data = await setUserData(user)
    
      return ctx.body = { ok : true, data : { userInfo : data }, message : '' }
    }
  } catch (e) {
    console.log(e)
  }

  return next()
}

auth.post('/login', isAuthenticated, ctx =>
  passport.authenticate('local', async (err, user, msg) => {
    const { driverToken } = ctx.request.body

    if(user) {
      await User.findByIdAndUpdate(user, { lastSession : Date.now() })
      await ctx.login(user)

      const data = await setUserData(user)

      return ctx.body = { ok : true, data : { userInfo : data }, message : '' }
    }

    ctx.status = 401 // unauthorized

    return ctx.body = { ok : false, data : null, message : msg }
  })(ctx)
)

auth.get('/check-auth', async ctx => {
  console.log(`User is ${ ctx.isAuthenticated() ? '' : 'not' } authenticated`)
  
  if(ctx.isAuthenticated()) {
    console.log('Inside, boys!')

    const data = await setUserData(ctx.state.user)

    return ctx.body = { ok : true, data : { userInfo : data }, message : '' }
  }

  return ctx.body = { ok : false, data : null, message : 'There is no saved session available' }
})
```

My situation is the following:

1. I refresh the page, a request to `/check-auth` is made, and ctx.isAuthenticated() returns false (as expected)
2. I log in, the session is stored and user logged. Nothing different.
3. I log out, ctx.logout() is called.
4. If I refresh the page, step 1 is made. Great, that's how's supposed to work, because I logged out. But if I reload while being logged in, `/check-auth` returns false.
5. If I try to log in after logging out, ctx.isAuthenticated() returns true.

Not sure if this is a bug, or if this is supposed to work like this.

My setup:
"koa": "next",
"koa-passport": "^4.0.1"
"koa-router": "^7.0.1"
"koa-session": "^5.5.1"

Any idea why is this happening? Or something I could work around? I tried the solution up there and it didn't work (passport returning undefined in `/check-auth`, on `ctx.session.passport`)

Bonus: If I set to request `/check-auth` after being logging out, it also returns false (including returning undefined when checking on `ctx.session.passport`, but if I log back in, the object exists.

Also, when I try to log in in another browser (different user, different cookies), the object appears with only one user, not storing the one already logged in, but instead overwriting it.

**Comment by peakman** [comment]
I’m pretty sure that in the end I resolved it by changing the order in which packages were initialised.

This is the order that worked for me.  At one time I had something different that worked with earlier versions but not the latest.

  app.use(session(sessionOptions, app));
  app.use(passport.initialize())
  app.use(passport.session())

Hope it might help.

Steve

**Comment by SkeLLLa** [comment]
Got the same problem, however latest solution doesn't work for me, I already have such order, but it still doesn't call deserialize method. However ctx.session is populated with correct session.

**Comment by rkusa** [comment]
> It seems this module is absolutely incompatible with koa-session when external session storage is used.

Looks like it, as also mentioned in other issues. If someone is going to provide a bare minimum app with this failing setup, I am willing to investigate. Other than that, there are other session middlewares out there that seem to work fine with an external session store.
