### ISSUE TITLE
Deserialization in Assets

### ISSUE THREAD

**Issue by nahtnam** [rkusa/koa-passport#102]
Hey,

I am having a problem where passport is deserializing on every single request, even requests to static assets like fonts and stylesheets. Is there any way to stop it? It feels like its a waste of a few sql statements.

Thanks.

**Comment by rkusa** [comment]
I might have to put `app.use(passport())` after `app.use(static())` in your middleware stack.

So

```js
app.use(static())

app.use(passport.initialize())
app.use(passport.session())
```

and not

```js
app.use(passport.initialize())
app.use(passport.session())

app.use(static())
```

Does this help?

**Comment by nahtnam** [comment]
Ah I see. That makes sense. I will do that.
