### ISSUE TITLE
4.0 changelog?

### ISSUE THREAD

**Issue by victorperin** [rkusa/koa-passport#111]
Where can I found information about what changed in this new version?

**Comment by rkusa** [comment]
https://github.com/rkusa/koa-passport/blob/master/CHANGELOG.md

## 4.0.1

- add `params` to `req` #110

## 4.0.0

- upgrade `passport` to 0.4
- add `ctx` getter to `req` #89

**Comment by victorperin** [comment]
Thanks :smile:
