### ISSUE TITLE
Passport deserializeUser is always invoked when getting static file.

### ISSUE THREAD

**Issue by thanhlq** [rkusa/koa-passport#116]
Hello Everybody,

I used koa-passport parallel with koa-static, when getting static files, passport initialize and user deserialized are always invoked... I see this really not necessary. Any tips for me to resolve this?

Thanks very much.

**Comment by rkusa** [comment]
Hi, doesn't adding the koa-static middleware before the passport middleware work?

**Comment by thanhlq** [comment]
Thanks for your answer - Already put before static. It seems because of something crashed in my koa app configuration. Today it works normally.

**Comment by rkusa** [comment]
Glad to hear it works now. Feel free to reopen the issue if the issue reappears.
