### ISSUE TITLE
koa-passport breaks node-inspector (remove Proxy)

### ISSUE THREAD

**Issue by iliakan** [rkusa/koa-passport#17]
Thanks for the great module.

Kind of cool that it uses ES6 Proxy, but that's too early. Right now ES6 Proxy are non-debuggable, see the discussion here https://github.com/node-inspector/node-inspector/issues/413.

Koa-passport is usually quite close to the top of the execution stream. When node-inspector meets proxy, it dies, effectively making all the application code below undebuggable.

(That's actually a suggestion, I don't have a stack, but koa-passport is the only module which uses ES6 proxy in the project, and node-inspector dies with that Proxy `Illegal access` error).

Given that the ES6 Proxy debugging issue is not going to be fixed soon, could you please remove it from the code and replace with something more-or-less stable please?

**Comment by davidragsdale** [comment]
The original linked ticket https://github.com/node-inspector/node-inspector/issues/413 indicates that the bug was resolved in Node 7.7+. Since that Node version is well beyond LTS, proxies should be able to be reintroduced.

**Comment by rkusa** [comment]
> The original linked ticket [node-inspector/node-inspector#413](https://github.com/node-inspector/node-inspector/issues/413) indicates that the bug was resolved in Node 7.7+. Since that Node version is well beyond LTS, proxies should be able to be reintroduced.

Thanks for the information! 👍

I'd really prefer going back to the Proxy implementation. However, I am not entirely sure if it is worth the hazel to go through possibly breaking people's usage of `koa-passport` with it 🤔

**Comment by shellscape** [comment]
@rkusa A new major version with updated `engines` range would solve that neatly. Node versions < 10 are now out of LTS and support for them can be safely dropped.
