### ISSUE TITLE
Mix of express/koa with passport in both breaks

### ISSUE THREAD

**Issue by Inoir** [rkusa/koa-passport#186]
If youve an koa app, with passport and mount an express app in there, also with passport, this lib produces errors.
This is happens cause of manipulation the global passport module, instead of just modify an instance.

So to point it out: https://github.com/rkusa/koa-passport/blob/8bf9697e53dcdf374a067148c103dfce3736eee3/lib/index.js#L12
This line is causing issues.

every passport used after the import of koa-passport will use the framework. This is maybe wanted in 99% of the use cases in my case this is breaking everything.

In my app the Koa auth happens first and is also successful, afterwards express is taking over and fails cause it also uses the koa-passport lib. Since i tried to only instantiate on instance with koa-passport (ive only possibility to edit the koa app, not the express) it should use the framework also only in this instance.

`const Instance = new passport.KoaPassport()`

Error:
```
TypeError: Cannot read property 'hasOwnProperty' of undefined
    at passportInitialize (******/node_modules/koa-passport/lib/framework/koa.js:27:18)
```

if i comment out this line, all works as i wanted it to work

**Comment by rkusa** [comment]
Would it help to not use the global instance in your express app?

```js
const instance = new passport.Passport()
```

**Comment by Inoir** [comment]
Like i said, ive done this. Maybe i should mention, im using esm modules, not commonjs. maybe this is the reason?
The passport.framework(...) call will be still executed and set the framework for every instance created after koa-passport is used. since i cant change the code of the express app, i need to make sure koa-passport is not setting this global or only in the instance.

Current workaround is to reset your settings after i imported koa-passport, so just set the default framework again.

Would still prefer to have an "better" solution for this. Seems this problem will maybe affect  more ppl, since esm modules is the new standard.

But like i said ive a working solution, so not rly a "bug" anymore. More a feature request to make this somehow configurable

**Comment by rkusa** [comment]
I am afraid that I feel like this is too much of an edge case (especially the part of not being able to adjust the express app) and thus not worth adding. Thanks for bringing this up anyway. I'll go ahead and close the issue, but anyone feel free to jump in if you have a similar requirement/use-case.
