### ISSUE TITLE
The problem with the mock

### ISSUE THREAD

**Issue by iliakan** [rkusa/koa-passport#19]
1) There's a need for `req, connection` property addressed by PR #18
2) There's a need to keep other properties bound to `req` when passed by passport. Maybe a foreach loop or an additional configuration will do.

The use case: I have `req.log` method which logs with request information (so I know the context). I also use `passReqToCallback: true` in strategies to have the `req` object (to log it and to merge profiles).

With the new koa-passport, `req.log` is undefined, so the project dies.

**Comment by mfornasa** [comment]
@iliakan could you provide a working mocking sample?

**Comment by iliakan** [comment]
@mfornasa What you mean?
