### ISSUE TITLE
Not generating oauth_token

### ISSUE THREAD

**Issue by snollygolly** [rkusa/koa-passport#25]
I have a strange problem, and I'm not even entirely sure it's with koa-passport, but I don't know where else to turn.

The code I'm using is pretty much exactly the code in the example, and up until recently, everything was working correctly.  I tried setting up a new machine to run my project, and I'm finding that on any new machine I try to set up, I can't get my app to send back an `oauth_token`.

I'm using the passport-twitter strategy only, and when I do a GET on http://127.0.0.1:3000/auth/twitter on one of my working computers, it responds back with:

`api.twitter.com/oauth/authenticate?oauth_token=XXX`

where `XXX` is the oauth_token.  When I do the same request on a non-working computer (same code, same everything else from what I can tell), I get:

`api.twitter.com/oauth/authenticate`

which obviously doesn't work.  I've tried everything I can think of to make this work and I'm absolutely stumped.  Any thoughts?

**Comment by rkusa** [comment]
Hi @snollygolly, have you compared the versions of your dependencies between the working and the new non-working computers?

**Comment by snollygolly** [comment]
Yep.  That's one of the things I tried last night. I did an `npm list` on both computers, compared them, and found some minor differences in packages.  I went through the list and did `npm remove --save package` and then `npm install --save package@version` on each package until they matched exactly.  No dice. :(

**Comment by rkusa** [comment]
Is it possible that you share your code (or a the authentication subset of it)?

**Comment by snollygolly** [comment]
Absolutely: http://github.com/snollygolly/bloodhound

The keys aren't included, but everything else is.

**Comment by snollygolly** [comment]
@rkusa We finally figured out the issue.  We followed koa's instructions to switch to `0.11`, but that automatically installs `0.11.15` which is what was causing the issue.  `0.11.14` works just fine though.

Sorry for wasting your time.  Maybe this will help someone else.

**Comment by rkusa** [comment]
No problem! I am glad you could solve your issue!

**Comment by janpieterz** [comment]
I encountered the same issue and reverting from 0.11.15 to 0.11.14 fixed it. Any idea @rkusa if this is an issue in koa-passport, passport or co?

**Comment by rkusa** [comment]
It is a `0.11.15` feature. But they are discussing about reverting this change.

The corresponding PR to passport-oauth1: jaredhanson/passport-oauth1#3

**Comment by janpieterz** [comment]
Thanks a lot!

**Comment by rkusa** [comment]
I think they have reverted the `url.format` change, i.e., it seems to work with `0.11.16` again.

**Comment by janpieterz** [comment]
Confirmed, got it working here with 0.11.16. Cheers for the update.
