### ISSUE TITLE
Does not work with koala

### ISSUE THREAD

**Issue by zia-newversion** [rkusa/koa-passport#32]
[Koala.js](https://github.com/koajs/koala) is packaged koa.js. When trying to get this to work with Koala.js, I found out that I couldn't authenticate even with correct username and password. (I was using [koa-passport-example](https://github.com/rkusa/koa-passport-example) as a reference). I am not an expert, but I tried to identify the issue.

I rewrote the koa-passport example to use koala instead of koa. It still didn't work. Then I tried to rewrite koa-passport-example to use koa, but instead use the modules that koala uses for specific purposes. I found that I can change everything and it works fine, except when I change it to use [koa-body-parsers](https://github.com/koajs/body-parsers) (which is what koala uses) instead of [koa-bodyparser](https://github.com/koajs/bodyparser) (which is what koa-passport-example is using), it doesn't work.

I think it has something to do with how koa-passport parses the body of of a POST request; that the piece of code used for this doesn't yield a good body when koa-body-parsers is used instead of koa-bodyparser. I found that with koa-body-parsers, I have to do `yield* this.request.json()` to get the request body, whereas with koa-bodyparser, I can do `this.request.body`.

Also I'm not sure whether I should be posting this here or over at koala repo, or at body-parsers repo. I'm not even sure if this is a problem caused by some stupid mistake I'm doing, however I've checked and double checked, and koa-passport-example works in every scenario except when using koa-body-parsers module instead of koa-bodyparser.

**Comment by rkusa** [comment]
:+1: for already tracking down this issue

As you already discovered, `koa-passport` expects to find an already parsed body at `this.request.body`. This is due to how `expressjs` and therefore `passport` handle the body. If you want to stick to `koa-body-parsers`, you probably have to add a middleware before `koa-passport` that parsers the body into `this.request.body`, e.g.:

```js
app.use(function*(next) {
  switch (this.request.is('json', 'urlencoded', 'multipart', 'image/*')) {
  case 'json':
    var body = yield* this.request.json();
    break;
  ...
  }

  this.request.body = body
  yield nest
})
```

**Comment by zia-newversion** [comment]
Awesome! Thanks!
