### ISSUE TITLE
Does not work with koa-better-body

### ISSUE THREAD

**Issue by chasm** [rkusa/koa-passport#33]
What is the trick to making this work with koa-better-body? The local strategy is never called.

Also, it would be nice if the documentation mentioned that the form fields for local MUST be called `username` and `password` or it simply won't work. That missing info cost me several hours of frustration, and I doubt that I'm the only one to have to deal with that.

**Comment by rkusa** [comment]
The form data is expected at `ctx.request.body`. As of the docs of `koa-better-body` this is done by default:

> patchKoa {Boolean} Patch request body to Koa's ctx.request object, default true

That is, first step would be to check that `ctx.request.body` is set properly.

> MUST be called username and password

`passport-local` has a `usernameField` and `passwordField` option that can be set to eg `email`. This specific docs request should go to `passport-local`. However, I agree that `koa-passport` could still use some doc improvements, e.g. in regarding body parser compatibilities.

**Comment by juanjoLenero** [comment]
Hi, I'm leaving this here since I ran into the same issue and found the solution:

`koa-better-body` by default places the parsed values under a `fields` and `files` key and this messes with the passport-local strategy which expects `username` and `password` to be at the root of the request body object.

```javascript
// Koa-better-body with default settings
// ... inside some middleware
console.log(this.request.body);
{
    fields: { // <--- passport-local doesn't know that the fields are nested inside this key.
        username: 'Pedro',
        password: 'qwerty'
    }
    files: undefined
}
```
So you need to get rid of that by using the `fieldsKey` option in `koa-better-body`:
```javascript
app.use(koaBody({fieldsKey: false}));

// ... inside some middleware.
console.log(this.request.body);
{
    username: 'Pedro', // The keys expected by passport local are no longer nested.
    password: 'qwerty',
    files: undefined // <--- you can also disable this with filesKey: false, but it's not necessary here.
}

```

**Comment by rkusa** [comment]
Thanks @juanjoLenero

**Comment by hardchor** [comment]
Hey. I'm using koala which uses yet another body parser, so had to extend the router generator like this:

```javascript
public.post('/login', function *() {
    this.request.body = yield this.request.urlencoded();
    yield passport.authenticate('local', {
        successRedirect: '/yesss',
        failureRedirect: '/noooo'
    })
})
```

**Comment by rkusa** [comment]
Thanks for the info @hardchor!
