### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by yanickrochon** [rkusa/koa-passport#37]
Can the deps be updated? I just figure that creating a fork and a PR just for that is dumb and anyone with access to origin:master could be able to do that in under a minute easily.

**Comment by epoberezkin** [comment]
+1

**Comment by rkusa** [comment]
Sure, will Update the dependencies as soon as I am back at work. Thanks for the note

**Comment by yanickrochon** [comment]
Good idea, @epoberezkin !

**Comment by rkusa** [comment]
Since `passport` updates are infrequent, I think keeping `passport` as a dependency is fine and easier.
