### ISSUE TITLE
Koa-password and twitter oauth1 integration

### ISSUE THREAD

**Issue by OrKoN** [rkusa/koa-passport#39]
Hi,

I am stuck with implementing the basic oauth1 flow for Twitter. I am trying to implement my own handling for `authenticate` middleware but I don't have access to the context in there:

```
router.get('/auth/twitter/callback',
  passportAuth.authenticate('twitter', function* (err, user, info, status) {
    if (!err) {
      this.redirect('http://localhost:4200/?id=' + user.id); // this is undefined
      return;
    }

    this.redirect('http://localhost:4200'); // this is undefined
  })
);
```

How to implement a custom processing of the redirection? Also is it possible to use passport w/o session? I am building a session-less server but it looks like passport for Twitter only works with session. 

Thanks in advance.

**Comment by rkusa** [comment]
Hi,

Does the following link help?
https://github.com/rkusa/koa-passport-example/blob/master/server.js#L38:50

Regarding the session. I've never uses passport without sessions. But maybe this question has already been asked and answered somewhere related to passport in general (and not for the wrapper Koa-passport)?

Best

**Comment by OrKoN** [comment]
Looks like that's the example I have overlooked. Thanks!
