### ISSUE TITLE
authorize functionality does not appear to work

### ISSUE THREAD

**Issue by danpantry** [rkusa/koa-passport#42]
When invoking `passport.authorize`, `this.req.account` is never set to the account from the strategy you are linking from. For example:

````javascript
const app = koa()
app.use(compose([passport.authenticate('local'), passport.authorize('facebook'), function *() {
  console.log(this.req.user) // this prints the local user as expected
  console.log(this.req.account) // this does not print the facebook account
}]))
````

`authorize` is used to link an existing authenticated account (in this case, `'local'`) with another provider. By default, according to passport docs, the newly linked account is placed in `req.account` in Express; the corresponding place for this would be `this.req.account` in `koa`.

**Comment by rkusa** [comment]
Hi, I've added a wrapper for the authorize method. However, I am not sure how it is meant to be used in `passport`. During testing, I had to use it for the facebook callback route:

```js
app.get('/auth/facebook/callback', passport.authorize('facebook'))
```

The `account` property will end up in `this.passport.account`.

**Comment by rkusa** [comment]
Please feel free to reopen the issue if the add `authorize` wrapper does not solve your issue.
