### ISSUE TITLE
"OAuthStrategy requires a verify callback"

### ISSUE THREAD

**Issue by basiclaser** [rkusa/koa-passport#48]
on line 7 im supposedly not defining a callback.. I'm not sure if the issue is with my syntax, koa-convert or koa-passport - can you see any problems with it ? 

```
OAuthStrategy requires a verify callback
```

```
import Strategy from 'passport-twitter';
import passport from 'koa-passport';
import Koa from 'koa';
let app = new Koa();

import convert from 'koa-convert';
app.use(convert(Strategy()))

export function initTwitterStrategy(){
var user = { id: 1, username: 'test' }
passport.serializeUser(function(user, done) {
  done(null, user.id)
})
passport.deserializeUser(function(id, done) {
  done(null, user)
})
passport.use(new Strategy({
    consumerKey: 'sYwaHTFjXet63oaeUlPSUic9',
    consumerSecret: 'Ka9Ds05LPtWqRrpO8SFPf8f7zJwROMasgN6ixzAhlPBKSl7kV',
    callbackURL: 'http://127.0.0.1:3000/auth/twitter/callback'
  },
  async (token, tokenSecret, profile, done) => {
    console.log("THIS HAPPENS?");
    await done(profile)
  }
))
}
```

**Comment by rkusa** [comment]
As the error suggests, the Twitter strategy seems to require some arguments. Additionally, you probably want `passport.use(new Strategy(...))` and not `passport.use(new Strategy(...))`.

**Comment by basiclaser** [comment]
>  you probably want passport.use(new Strategy(...)) and not passport.use(new Strategy(...))

was this a typo? thanks for your help

**Comment by rkusa** [comment]
yeah, I meant

> you probably want `passport.use(new Strategy(...))` and not `app.use(new Strategy(...))`.

(add strategy to passport and not to the koa app)

**Comment by marr** [comment]
you'd also want to call `done(null, profile)` instead of `done(profile)`

**Comment by christiansakai** [comment]
when calling done(null, profile), where does the profile get appended at the next middleware? is it at ctx?

**Comment by rkusa** [comment]
Where are you calling `done(null, profile)`? If you are looking for the user, he is available at `ctx.passport.user`.

**Comment by rkusa** [comment]
Feel free to reopen the issue if it still persists
