### ISSUE TITLE
with koa-session2

### ISSUE THREAD

**Issue by rimmartin** [rkusa/koa-passport#54]
Hi,

I'm trying to use this with koa-session2 since both support v2.x.  The ctx.isAuthenticated() is never true 

```
// Require authentication for now
app.use(function (ctx, next) {
  console.dir('url: '+ctx.originalUrl+' auth?: '+ctx.isAuthenticated());     //ctx.isAuthenticated() never true
  if (!ctx.originalUrl.startsWith("/b2b/") || ctx.isAuthenticated()) {
    return next();
  } else {
    ctx.redirect('/');
  }
});

```
I do see the user and password work.  Most of the code I'm testing is based on the https://github.com/mapmeld/koa-passport-example mongo example.

This example runs for me on nodejs 6.2.0.  Is there any example or test with koa-session2?

**Comment by rkusa** [comment]
Hi, just tested `koa-session2` with [`rkusa/koa-passport-example`](https://github.com/rkusa/koa-passport-example). It worked perfectly fine. Maybe comparing your implementation with this example helps finding the issue?

**Comment by rimmartin** [comment]
What does your code look like for tying in koa-sesion2?  You ran it through babel?

```
import session from "koa-session2";


app.use(session({
    key: "SESSIONID",   //default "koa:sess" 
}));
```

**Comment by rkusa** [comment]
```js
const session = require('koa-session2').default
app.use(session())
```

Didn't use babel (therefore the `.default`)

**Comment by rimmartin** [comment]
ah, never heard of a .default before; interesting.

Thank you, this gives me a basis to start
