### ISSUE TITLE
Cannot get next tag from npm

### ISSUE THREAD

**Issue by bingomanatee** [rkusa/koa-passport#55]
DAVIDs-iMac:eatYourFriends2017 dave$ npm install koa-passport@next --verbose
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   'koa-passport@next',
npm verb cli   '--verbose' ]
npm info using npm@3.10.2
npm info using node@v4.4.6
npm verb request uri https://registry.npmjs.org/koa-passport
npm verb request no auth needed
npm info attempt registry request try #1 at 10:48:47 AM
npm verb request id 97b017e43a216619
npm verb etag "AKM6RWDK5HFO11UKSSGV64Q3C"
npm http request GET https://registry.npmjs.org/koa-passport
npm http 304 https://registry.npmjs.org/koa-passport
npm verb headers { date: 'Fri, 01 Jul 2016 17:48:47 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: '"AKM6RWDK5HFO11UKSSGV64Q3C"',
npm verb headers   age: '99',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-lax1437-LAX',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '1',
npm verb headers   'x-timer': 'S1467395327.705426,VS0,VE0',
npm verb headers   vary: 'Accept-Encoding' }
npm verb etag https://registry.npmjs.org/koa-passport from cache
npm verb get saving koa-passport to /Users/dave/.npm/registry.npmjs.org/koa-passport/.cache.json
npm verb correctMkdir /Users/dave/.npm correctMkdir not in flight; initializing
npm verb cache add spec koa-passport@next
npm verb addNamed "next" is being treated as a dist-tag for koa-passport
npm info addNameTag [ 'koa-passport', 'next' ]
npm verb addNameTag registry:https://registry.npmjs.org/koa-passport not in flight; fetching
npm verb get https://registry.npmjs.org/koa-passport not expired, no request
npm verb addNamed "2.1.1" is a plain semver version for koa-passport
npm verb afterAdd /Users/dave/.npm/koa-passport/2.1.1/package/package.json not in flight; writing
npm verb correctMkdir /Users/dave/.npm correctMkdir not in flight; initializing
npm verb afterAdd /Users/dave/.npm/koa-passport/2.1.1/package/package.json written
npm verb request uri https://registry.npmjs.org/passport
npm verb request no auth needed
npm info attempt registry request try #1 at 10:48:48 AM
npm verb etag "536JQUIE2ZILIC75GIQCVNSZT"
npm http request GET https://registry.npmjs.org/passport
npm http 304 https://registry.npmjs.org/passport
npm verb headers { date: 'Fri, 01 Jul 2016 17:48:48 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: '"536JQUIE2ZILIC75GIQCVNSZT"',
npm verb headers   age: '257',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-lax1437-LAX',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '2',
npm verb headers   'x-timer': 'S1467395328.936120,VS0,VE0',
npm verb headers   vary: 'Accept-Encoding' }
npm verb etag https://registry.npmjs.org/passport from cache
npm verb get saving passport to /Users/dave/.npm/registry.npmjs.org/passport/.cache.json
npm verb correctMkdir /Users/dave/.npm correctMkdir not in flight; initializing
npm verb cache add spec passport@^0.3.0
npm verb addNamed ">=0.3.0 <0.4.0" is a valid semver range for passport
npm verb addNameRange registry:https://registry.npmjs.org/passport not in flight; fetching
npm verb get https://registry.npmjs.org/passport not expired, no request
npm verb addNamed "0.3.2" is a plain semver version for passport
npm verb afterAdd /Users/dave/.npm/passport/0.3.2/package/package.json not in flight; writing
npm verb correctMkdir /Users/dave/.npm correctMkdir not in flight; initializing
npm verb afterAdd /Users/dave/.npm/passport/0.3.2/package/package.json written
npm verb request uri https://registry.npmjs.org/pause
npm verb request no auth needed
npm info attempt registry request try #1 at 10:48:48 AM
npm verb etag "AMXJRF8IYEDH2W7ZVFJ83MJR8"
npm http request GET https://registry.npmjs.org/pause
npm http 304 https://registry.npmjs.org/pause
npm verb headers { date: 'Fri, 01 Jul 2016 17:48:49 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: '"AMXJRF8IYEDH2W7ZVFJ83MJR8"',
npm verb headers   age: '298',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-lax1437-LAX',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '3',
npm verb headers   'x-timer': 'S1467395329.020608,VS0,VE0',
npm verb headers   vary: 'Accept-Encoding' }
npm verb etag https://registry.npmjs.org/pause from cache
npm verb get saving pause to /Users/dave/.npm/registry.npmjs.org/pause/.cache.json
npm verb correctMkdir /Users/dave/.npm correctMkdir not in flight; initializing
npm verb cache add spec pause@0.0.1
npm verb addNamed "0.0.1" is a plain semver version for pause
npm verb addNameVersion registry:https://registry.npmjs.org/pause not in flight; fetching
npm verb get https://registry.npmjs.org/pause not expired, no request
npm verb afterAdd /Users/dave/.npm/pause/0.0.1/package/package.json not in flight; writing
npm verb correctMkdir /Users/dave/.npm correctMkdir not in flight; initializing
npm verb afterAdd /Users/dave/.npm/pause/0.0.1/package/package.json written
npm verb correctMkdir /Users/dave/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /Users/dave/.npm/_locks/staging-d0ae6657fa36e412.lock for /Users/dave/Documents/repos/eatYourFriends2017/node_modules/.staging
npm verb unbuild node_modules/.staging/koa-passport-2440a681
npm verb gentlyRm don't care about contents; nuking /Users/dave/Documents/repos/eatYourFriends2017/node_modules/.staging/koa-passport-2440a681
npm verb tar unpack /Users/dave/.npm/koa-passport/2.1.1/package.tgz
npm verb tar unpacking to /Users/dave/Documents/repos/eatYourFriends2017/node_modules/.staging/koa-passport-2440a681
npm verb gentlyRm don't care about contents; nuking /Users/dave/Documents/repos/eatYourFriends2017/node_modules/.staging/koa-passport-2440a681
npm verb gentlyRm don't care about contents; nuking /Users/dave/Documents/repos/eatYourFriends2017/node_modules/.staging/koa-passport-2440a681/node_modules
npm info lifecycle koa-passport@2.1.1~preinstall: koa-passport@2.1.1
npm info linkStuff koa-passport@2.1.1
npm verb linkBins koa-passport@2.1.1
npm verb linkMans koa-passport@2.1.1
npm info lifecycle koa-passport@2.1.1~install: koa-passport@2.1.1
npm info lifecycle koa-passport@2.1.1~postinstall: koa-passport@2.1.1
npm verb unlock done using /Users/dave/.npm/_locks/staging-d0ae6657fa36e412.lock for /Users/dave/Documents/repos/eatYourFriends2017/node_modules/.staging
react-redux-starter-kit@3.0.0-alpha.0 /Users/dave/Documents/repos/eatYourFriends2017
`-- koa-passport@2.1.1  invalid

**Comment by rkusa** [comment]
```
% npm install koa-passport@next
~/Downloads
└─┬ koa-passport@2.1.1
  └─┬ passport@0.3.2
    ├── passport-strategy@1.0.0
    └── pause@0.0.1
```

Does work for me... Maybe try a `npm cache clean`

**Comment by rkusa** [comment]
Please reopen if it still does not work
