### ISSUE TITLE
Support ctx.state to pass user

### ISSUE THREAD

**Issue by gingerich** [rkusa/koa-passport#57]
I believe that best practice for koa v2 would be to store the authenticated user in `ctx.state`, rather than `ctx.request`.

Documentation for koa v2 indicates that `ctx.state` is "the recommended namespace for passing information through middleware ..."
https://github.com/koajs/koa/blob/v2.x/docs/api/context.md#ctxstate

**Comment by rkusa** [comment]
Sounds good to me. What do you think, should we still keep it in `ctx.request` with a deprecation warning for now?

**Comment by gingerich** [comment]
Yeah I think that makes sense. I can put together I PR for this if you want

**Comment by rkusa** [comment]
A PR is of course highly welcome, but I am also totally fine with implementing it myself.

**Comment by gingerich** [comment]
I'd love to contribute. I'll take a stab at it and see what you think.

**Comment by gingerich** [comment]
#58

**Comment by rkusa** [comment]
Before I publish a new version I just like to get some feedback on the methods `.login()`, `.logout()`, `.isAuthenticated()` and `.isUnauthenticated()`. They are currently added to both `ctx` and `ctx.req`. I would also like to clean this up a little bit. What is your opinion for the best location where to put them, `ctx` or also `ctx.state`?

**Comment by gingerich** [comment]
I tend to think of `ctx.state` as a simple data store, where logic does not belong, so my preference would be for `ctx`.
However, `.isAuthenticated()` and `.isUnauthenticated()` pertain more to a specific request (depending whether sessions are used), so I could see an argument for adding those two to `ctx.req`.
It's hard to say what's best, but if I had to choose one place for all methods, I think `ctx` makes the most sense.

**Comment by rkusa** [comment]
Thanks for your feedback! I agree on your points. I think `.isAuthenticated()` and `.isUnauthenticated()` fit into both `ctx` and `ctx.request` (`request` should probably preferred over `req`). But since having it both does not make too much sense, I will probably go with `ctx`.

**Comment by gingerich** [comment]
Before you publish, I just discovered a problem with my implementation that could create a race condition.

Basically, `next()` can be called before `ctx.state.user` is assigned because `resolve` callback is invoked first.

I'll fix in a new PR

**Comment by jeffijoe** [comment]
This can be a problem when using other middleware that relies on `ctx.req.user` - in particular [oauth0orize](https://github.com/ortoo/oauth2orize). Any way to turn off the deprecation notice?

**Comment by rkusa** [comment]
Thanks for reporting, I've created an issue for this: #66
