### ISSUE TITLE
Branch v2.x : Question  passport.initialize()

### ISSUE THREAD

**Issue by guygit** [rkusa/koa-passport#59]
Hi there,

I 'd like to use "koa-passport" with "koa-jwt-redis-session" to avoid cookies for session handling.

Do you happen to know if the call to "passport.initialze()" is needed in such a scenario?

Please note, I'm using branch "v2.x"

I'm asking this, cause it seems to work even without doing so ..

Thx a lot

**Comment by rkusa** [comment]
Yes, as I know is `passport.initialze()` still needed. You can, however, skip the call to `passport.session()`.

**Comment by guygit** [comment]
Dank Dir :-)
