### ISSUE TITLE
passport facebook route 404 error

### ISSUE THREAD

**Issue by proua** [rkusa/koa-passport#61]
Versions
```
"koa-passport": "^1.3.0"
"koa-router": "^5.4.0"
NodeJS 6.1.0
```

I get 404 error when use koa-passport and koa-router in my app
my route file
```javascript
const Router = require('koa-router');
const passport = require('koa-passport');

function register (app) {
    const router = new Router({
        prefix: '/auth'
    });
    router.get('/facebook', function* () {
        passport.authenticate('facebook');
    });
    app.use(router.routes());
    app.use(router.allowedMethods());
}

module.exports = register;
```
app.js

```javascript
app.use(passport.initialize());
app.use(passport.session());
//....
require('./app/server/routes/auth.route')(app);
```
When I go to the '/auth/facebook' route I get 'Page not Found' error.
If I comment passport.authenticate('facebook'); line route works fine with something like this.body = 'facebook login';

Thanks

**Comment by rkusa** [comment]
Hi @proua, I would be happy to help you. But could you please take some time to do some basic formatting of your issue (distinguish between code and non-code). The Github textarea provides buttons for doing so. Thanks

**Comment by proua** [comment]
Sorry, my mistake.

**Comment by rkusa** [comment]
Thanks :-)

Does the following work?

```
router.get('/facebook', passport.authenticate('facebook'));
```

**Comment by proua** [comment]
Upps....
I am ashamed (

Thanks, it is works

**Comment by rkusa** [comment]
You are welcome
