### ISSUE TITLE
No ctx.state.user on custom login in subsequent middleware

### ISSUE THREAD

**Issue by wlingke** [rkusa/koa-passport#70]
If I do the following:

```
app.use(route.post('/custom', function(ctx, next) {
  return passport.authenticate('local', async function(user, info, status) {
    if (user === false) {
      ctx.status = 401
      ctx.body = { success: false }
    } else {
      await ctx.login(user)
      next()
    }
  })(ctx, next)
}))
```

My next middleware shows that `ctx.state.user` is `undefined`

**Comment by rkusa** [comment]
Hi, thanks for reporting! Which version are you using? If `3.0.0-rc.1`, it must be `function(err, user, info, status)` instead of `function(user, info, status)` (I forgot to update `koa-passport-example`).

**Comment by wlingke** [comment]
Not at my computer right now so unsure which version but 'user' was available and was the right value. I checked that value.

**Comment by rkusa** [comment]
It is probably `v2.x` then. The `ctx.state.user` handling has been improved in `3.0.0-rc.1`. I will have a look at how to fix this for `v2.x`. In the meantime, it should work with `3.0.0-rc.1`.

**Comment by wlingke** [comment]
Great thanks!
ᐧ
