### ISSUE TITLE
Help with the right use implementation 

### ISSUE THREAD

**Issue by sschenk** [rkusa/koa-passport#74]
I'm trying to use passport with a local login strategy. First I'm doing some simple non passport validation to check the email field (used for login) and password fields are not empty and such.

Then I'm launching a local passport strategy to check the login input against my MongoDB connection.

I can get my passport check to work - I can print the error about a wrong user credentials to the console.log for example - but I don't know how to pass that data back to the koa router.

Here's some sample code to illustrate:
```

//passport
var passport = require('koa-passport')

// Body parser
app.use(bodyParser())

// Start the router instance
var router = require('koa-router')()
app.use(passport.initialize())

//Require form validation
validateLoginForm = require('./forms/validation')

// Require strategy  
const localLoginStrategy = require('./passport/local-login')
passport.use('local-login', localLoginStrategy)

router.post('/api/login', function* (next){
  this.body = this.request.body
  // Simple validation of the login form
  const validationResult = validateLoginForm(this.body)
  if (!validationResult.success){ 
    yield this.body = {
    success: false,
    message: validationResult.message,
    errors: validationResult.errors
    }
  }
  yield passport.authenticate('local-login', function* (err, token, userData, next) { 
    console.log(err)
    yield {erro:err}
  })
    //I Want to yield my passport check result here so I can do this.body={err}
    }) 
```

I've tried looking over your example, but it just make me think my implementation might be wrong.

**Comment by sschenk** [comment]
Has to do something like ctx = this to pass the request inside the generator, But my implementation still seems sketchy

**Comment by rkusa** [comment]
Have a look at [this](https://github.com/rkusa/koa-passport-example/blob/koa-passport%401.x/server.js#L38-L50) if you are using `v1.x` or [this](https://github.com/rkusa/koa-passport-example/blob/koa-passport%402.x/server.js#L32-L42) if you are using `v2x`. Does this help?

**Comment by rkusa** [comment]
I've checked this issue again. As seen in the linked lines in my previous response, I am also doing `.call(this, next)` to the the context into the authenticate function. Not very beautiful indeed. The usage of async/await and arrow functions makes this a little bit nicer.
