### ISSUE TITLE
arguments being passed are in incorrect order

### ISSUE THREAD

**Issue by reharik** [rkusa/koa-passport#75]
Hi, I have a login route and inside it I do 
`return koapassport.authenticate('local', function(err, user, info, status) {`
when I log out the args ( on what should be a successful login ), user, info and status are all null, and err is equal to my user object.  
I'm defining my local strategy just like in the examples.  Not sure quite what's going on.
I've read through the source code for koa-passport and local-passport and don't see what's happening.  I guess the next step for me is to dig into passport source call, because if I"m not mistaken you are internally handing the call back to the passport.authenticate method, so perhaps something has chnaged in there.
I'm using koa-passport 2.2.2
Thanks,
Raif

**Comment by rkusa** [comment]
I'll check that in the next couple of days. Thanks for reporting!

**Comment by rkusa** [comment]
So finally, I think this is the same issue as #69. That is, version `3.0.0-rc.1` should solve it?

**Comment by reharik** [comment]
well, not for me.  I'm re-writing passport in a more functional less state driven, no callbacks kind of way.  I just can't take it anymore.  Almost done. 
So I don't want you to take any action on my behalf. 
Thank you,
R

**Comment by rkusa** [comment]
Please keep us updated. Having a good less-hacky authentication solution for koa would be great!

**Comment by reharik** [comment]
Hey, I've published my promise driven authentication strategy framework.  it's called papers, I have a koa-papers as well, because as you know what it passes to middleware is a bit different. 
I currently have three strategies published ( only two anyone will care about, the third is LTI for LMS' ) local, and jwt.
It has pretty full feature parity with passport and is much cleaner code.  The strategies are very easy to port, so if people want one of the existing strategies for passport they ( or I ) can port them to papers very easily.
I did not create the koa2 version because I was getting some strange behavior from babel when I compiled it, but I'm running it on koa2 with convert in my own projects.  If you feel this is important I can figure it out, otherwise I'll wait till node 7 comes out.
Please let me know what you think and/or help me publicize this package.  I don't really know how to get traction with it.
Thanks you,
Raif
https://www.npmjs.com/package/papers
https://www.npmjs.com/package/koa-papers
https://www.npmjs.com/package/papers-local
https://www.npmjs.com/package/papers-jwt
https://www.npmjs.com/package/papers-lti

**Comment by reharik** [comment]
will you look at that, I just noticed that node 7 was just released.  I believe you have to use node --harmony-async-await flag though

**Comment by reharik** [comment]
Hey, I've published my promise driven authentication strategy framework.
 it's called papers, I have a koa-papers as well, because as you know what
it passes to middleware is a bit different.
I currently have three strategies published ( only two anyone will care
about, the third is LTI for LMS' ) local, and jwt.
It has pretty full feature parity with passport and is much cleaner code.
The strategies are very easy to port, so if people want one of the existing
strategies for passport they ( or I ) can port them to papers very easily.
I did not create the koa2 version because I was getting some strange
behavior from babel when I compiled it, but I'm running it on koa2 with
convert in my own projects.  If you feel this is important I can figure it
out, otherwise I'll wait till node 7 comes out.
Please let me know what you think and/or help me publicize this package.  I
don't really know how to get traction with it.
Thanks you,
Raif
https://www.npmjs.com/package/papers
https://www.npmjs.com/package/koa-papers
https://www.npmjs.com/package/papers-local
https://www.npmjs.com/package/papers-jwt
https://www.npmjs.com/package/papers-lti

**Comment by rkusa** [comment]
Hi @reharik thanks for the update! I never really did active promotion for NPM modules, but hackernews and reddit could work to get some initial momentum. I did a quick peak into your code. I would recommend to run some linting tools. E.g. you have some inconsistency when using `var` or `const` and there are also cases where you seem to use non of them making variables to pollute the global scope.
