### ISSUE TITLE
login in controller not actually called

### ISSUE THREAD

**Issue by lookis** [rkusa/koa-passport#77]
version: 1.3.0

When login a user in controller, I found the function not really called. the login function return a bound Function:
https://github.com/rkusa/koa-passport/blob/master/lib/framework/koa.js#L46-L48

I am supposed it should actually call the delegate login:

>     ctx.login = ctx.logIn = function(user, options) {
      return login.bind(req)(user, options)
    }

**Comment by rkusa** [comment]
Thanks for reporting this! However, this is the intended behaviour, since the method is meant to be called as follows `yield ctx.login(user)`

**Comment by lookis** [comment]
thx for explain.
