### ISSUE TITLE
Some odd problems with custom strategies

### ISSUE THREAD

**Issue by wlingke** [rkusa/koa-passport#78]
When creating a custom strategy: 

```
app.use(
(ctx, next) =>
  passport.authenticate('local',
  async (err, user, info, status) => {
    if (err) {
      ctx.status = 401;
      return;
    }
    if (user === false) {
      ctx.status = 401;
      return;
    }

    await ctx.login(user, { session: false })
    next()
  }
)(ctx, next),

async (ctx, next) => {
    //ctx.state.user is available here
    //DO SOME ASYNC STUFF (none of these is throwing errors)
    await something;

    ctx.status = 200;
    console.log(ctx.status) //shows 200
}
)
```

The result from this is a 404 status for some reason. 

There's also a separate but possibly related issue of not being able to use `ctx.throw` inside the (err, user, info, status) function. It ends up also sending a 404 status instead of whatever I'm throwing though this isn't as big of a problem.

Not sure if I am just misunderstanding how to use this, but I simply want to do a custom login, then have a middleware after that does some async stuff and sends some data to client.

**Comment by wlingke** [comment]
It seems like the key is the below instead of what I had above. Not exactly sure why this made the difference to be honest. 
```
await ctx.login(user, { session: false }).then(next)
```

**Comment by rkusa** [comment]
Hi, I think it should be

```
await ctx.login(user, { session: false })
await next()
```

which is in the end the same as your 

```
await ctx.login(user, { session: false }).then(next)
```

**Comment by wlingke** [comment]
Got it - that's right. Thanks so much!

**Comment by rkusa** [comment]
Cheers, and sorry for the late response!
