### ISSUE TITLE
Declaration files Typescript

### ISSUE THREAD

**Issue by arcanewater** [rkusa/koa-passport#79]
Has anyone worked with Typescript 2? And are there maybe any plans to write declaration files for koa-passport?

**Comment by rkusa** [comment]
I haven't worked with Typescript. Does `passport` (since koa-passport is more or less just a wrapper) provide such files?

**Comment by arcanewater** [comment]
Yea passport have them: https://www.npmjs.com/package/@types/passport
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/types-2.0/passport

I am experimenting a bit but no success yet.

**Comment by rkusa** [comment]
It would be necessary to also have such files for all the passport strategies used, wouldn't it?

**Comment by arcanewater** [comment]
Most of types are already here for example local: https://www.npmjs.com/package/@types/passport-local. So i think only need there should be function which are not passport fun.

**Comment by arcanewater** [comment]
Its done, one guy already pushed it to DefinitlyTyped

**Comment by rkusa** [comment]
Thanks for the update! Just for future reference, link is: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/koa-passport/koa-passport.d.ts
