### ISSUE TITLE
What's wrong

### ISSUE THREAD

**Issue by YanLobat** [rkusa/koa-passport#80]
I am extremely sorry but I don't understand what't wrong with my example?
[Index file](https://github.com/YanLobat/Crystal/blob/master/index.js) 

I need just basic auth want to type test username and test password and redirect to success page

**Comment by rkusa** [comment]
What exactly does not work?

**Comment by YanLobat** [comment]
I wanna see basic auth
default page should display login POST form(this ok) with action `/login`
But it seems my post route /login doesn't work at all
@rkusa

**Comment by rkusa** [comment]
Please try out `koa-passport` v`2.x` (or even better, already `koa-passport`@`3.0.0-rc.1`), which is meant to be used for `koa` v`2.x`.

**Comment by YanLobat** [comment]
It seems get it
Main problem was babel and async/await. I think they doesn't work well yet.

**Comment by YanLobat** [comment]
Is there any way to combine it?

**Comment by rkusa** [comment]
Sorry don't understand the question? `koa-passport`@`3.0.0-rc.1` should work fine with async/await

**Comment by rkusa** [comment]
Please reopen if the issue still exists
