### ISSUE TITLE
serializeUser and deserializeUser never called

### ISSUE THREAD

**Issue by dagda1** [rkusa/koa-passport#83]
My `server.js` file looks like this:

```
import Router from 'koa-router';
import error from './middleware/Error';
import TokenAuth from './middleware/TokenAuth';
import helmet from 'koa-helmet';
import passport from 'koa-passport';
import './config/Passport';
import convert from 'koa-convert';
const session = require('koa-generic-session')

const cors = require('kcors');

const app = new Koa();

app.use(parser({
  onerror: (error, ctx) =>{
    ctx.status = 422
    ctx.body =
      {
        message: "Unable to parse request body."
      }
  }
}));

app.use(cors({
  origin: 'http://localhost:4040'
}));

app.use(helmet());
app.use(logger());
app.use(error());

app.keys = ['the-session-secret'];
app.use(convert(session()));

app.use(passport.initialize());
app.use(passport.session());

const publicRouter = new Router({
  prefix: '/api'
});

publicRouter.use('/managers', managerRoutes.routes());

app.use(publicRouter.routes())
   .use(publicRouter.allowedMethods());

const privateRouter = new Router({
  prefix: '/admin'
});

privateRouter.use(TokenAuth);

privateRouter.use(adminRoutes.routes());

app.use(privateRouter.routes())
   .use(privateRouter.allowedMethods());

const authRouter = new Router({
  prefix: '/auth'
});

authRouter.use(authRoutes.routes());

app.use(authRouter.routes())
   .use(authRouter.allowedMethods());

app.listen(config.site.port);

export default app;
```
My `auth` route looks like this:

```
import jwt from 'jsonwebtoken';
import Router from 'koa-router';
import passport from 'koa-passport';

import { config } from '../config/config';

const router = new Router();

router.post('/', function(ctx, next) {
  return passport.authenticate('local', function(err, user, info, status) {
    if(user === false) {
      ctx.status = 401
      ctx.body = {error: 'Invalid Credentials provided'};
      return;
    }

    const opts = {
      expiresIn: config.token.expires
    };

    const response = user.toJSON();

    delete response.created_at;
    delete response.updated_at;
    delete response.password;
    delete response.salt;

    const token = jwt.sign(response, config.token.secret, opts);

    ctx.body = {token};
    ctx.status = 201;
  })(ctx, next)
})

export default router;

```

I am suspicious of the function that I am passing into `passport.authenticate` as I am not actually returning anything or I am not sure if I should be calling login.

My `passport.js` file looks like this:
```

import passport from 'koa-passport';
import User from '../models/User';
import Strategy from 'passport-local';

passport.serializeUser((user, done) => {
  console.log('in serializeUser');
  done(null, user.id);
});

passport.deserializeUser(async (id, done) => {
  try {
    console.log('in deserializeUser');
    const user = await User.findById(id);
    done(null, user);
  } catch(err) {
    done(err);
  }
});

passport.use('local', new Strategy({
  usernameField: 'username',
  passwordField: 'password'
}, async (username, password, done) => {
  try {
    const user = await User.where({
      username
    }).fetch();

    if (!user) {
      return done(null, false)
    }

    try {
      const isMatch = await user.validatePassword(password);

      if (!isMatch) {
        return done(null, false)
      }

      done(null, user)
    } catch (err) {
      done(err)
    }

  } catch (err) {
    return done(err)
  }
}));
```
Neither `serializeUser` nor `deserializeUser` are ever called and I do not understand why.

Is the function that I am passing into `passport.authenticate` wrong?

**Comment by dagda1** [comment]
Is there something wrong with the way  I have worded the question?

**Comment by rkusa** [comment]
Hi @dagda1, your question is fine, I just was on vacation. What version of `koa-passport` are you using?

**Comment by dagda1** [comment]
Thank you for responding.

I am using koa-passport@^3.0.0-rc.1

**Comment by rkusa** [comment]
Does adding a `return ctx.login(user)` at the end of `passport.authenticate` help?

**Comment by dagda1** [comment]
Yes that ensures serializeUser is called.  What I am looking to do is have `ctx.user` set on the server for the session so that I don't have to pass the id back to the client.

How can I ensure that it set?

**Comment by rkusa** [comment]
Looking at your example (considering you have added the `ctx.login`) it should actually already work. The user should be at `ctx.state.user`. Is this the case?

**Comment by dagda1** [comment]
yes, it works.  Brilliant, thanks!

**Comment by dagda1** [comment]
I really apologise about reopening but deserializeUser is not called.  I am confused as to when this should be called.

What I want to get away from is having the id in the jwt that is returned to the client.

When should I set `ctx.state.user` and how can I then ensure it is in the session on each request that has a valid jwt without storing the id in the jwt on the client.

**Comment by rkusa** [comment]
I cannot spot an error in your implementation, yet. `ctx.state.user` should be set automatically once a user is logged in. Passport should set a cookie containing the information you returned in `serializerUser`. If such a cookie is found, the `deserializeUser` is called with this information, which is the user id in you case. That is, you do not need to have the user id in the jwt, because it is saved in the cookie (in a encrypted way).

I've updated [koa-passport-example](https://github.com/rkusa/koa-passport-example) to make use of async/await and in this example, `deserialzeUser` is called properly and I don't really see a difference to your implementation.

Something else: a goal of using JWTs is to do not have to use sessions. So you are mixing up two different authentication approaches. If you are doing this on purpose, this is of course fine. If you are just going to use JWT for authentication, I would actually ditch the `koa-passport` dependency. Because all you need is a route the checks username and password and creates a JWT accordingly. If you need to restore a user from a cookie, you can also save the JWT to a cookie (but make sure to save it using `HttpOnly` and `Secure` flags; and very important, take means to protect the token against CSRF!).

**Comment by dagda1** [comment]
Thank you for the advice.  I removed koa-passport
