### ISSUE TITLE
Update Example in the docs to use koa-session2

### ISSUE THREAD

**Issue by etherealite** [rkusa/koa-passport#99]
Would it be worth changing the example in the [docs](https://github.com/rkusa/koa-passport/blob/3.0.0-rc.3/README.md) from koa-generic-session to koa-session2? I see no evidence that the author of koa-generic-session is planning on supporting Koa 2 in a timely manner.

**Comment by rkusa** [comment]
Sounds good. Are you maybe aware of the differences between [`koa-session`](https://github.com/koajs/session) and `koa-session2`?

**Comment by etherealite** [comment]
I'm afraid I'm not aware of any differences in interface or semantics. Once I have more experience with koa-session2  I'll report back

**Comment by etherealite** [comment]
Looks like koa-session2 is far fro API compatible from koa-generic-session. From the activity that I'm seeing in the issue tracker for koa-generic-session, someone has already made an API compatible port to Koa2 called [koa-session-minimal](https://github.com/longztian/koa-session-minimal). Waiting to see if the Koa org merges with this new project is probably the best thing to do at the moment.

**Comment by rkusa** [comment]
I have replaced `koa-generic-session` with `koa-session` for now (just decided on the fact that it lives int the `koajs` org) to get rid of `koa-convert`. Thanks for bringing this up!

https://github.com/rkusa/koa-passport-example/commit/7de29cf3c57f02e3db8ccea73bb5fcc3e8a09fd1

**Comment by etherealite** [comment]
It was my pleasure.

**Comment by lukeramsden** [comment]
@etherealite The docs don't appear to be up to date with that then

**Comment by etherealite** [comment]
@lukeramsden When you say 
>The docs don't appear to be up to date with that then

 I'm not sure which docs you are referring to, nor what particular changes such documents would require.

Can you please clarify?

**Comment by lukeramsden** [comment]
@etherealite I'm referring to [this](https://github.com/rkusa/koa-passport#usage)

**Comment by rkusa** [comment]
@lukeramsden Good find, will be updated, thanks!
